test_proc:
  outputs:
    dev:
      type: snowflake
      account: oe13380.ap-southeast-1
      database: TEST_SNOWFLAKE
      # authenticator: externalbrowser
      password: Erding!1
      role: ACCOUNTADMIN
      schema: SCHEMA1
      threads: 4
      user: ANBARASURAM
      # user: anbu.myid@gmail.com
      warehouse: TEST_PROC_WH
      # proxy_host: 'http://proxy.cat.com'
      # proxy_port: 80
  target: dev

# procurement:
#   target: dev                         # default configuration
#   # target: adl_app_analytics
#   outputs:
#     # ADL DEV Profile
#     dev:
#       type: snowflake
#       account: cat_ohio.us-east-2.aws
 
#       # SSO config
#       authenticator: externalbrowser
#       user: anbarasu.ramachandran@cat.com
#       role: MASTER_RAMACA6_ROLE
#       database: PROCUREMENT_ANALYTICS_DEV_DB
#       warehouse: PROCUREMENT_ANALYTICS_SNOWPARK_WH
#       schema: ADL
#       threads: 8
#       proxy_host: 'http://proxy.cat.com'
#       proxy_port: 80
#       # optional
#       connect_retries: 0 # default 0
#       connect_timeout: 30 # default: 10
#       client_session_keep_alive: True
#       retry_on_database_errors: False # default: false
#       retry_all: True  # default: false
#       reuse_connections: True # default: false